// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/artikel/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/artikel/[id]').default>>>>
    }
    '/api/artikel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../.../../server/api/artikel/index.postfault>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/artikel/index.post').default>>>>
    }
    '/api/artikel/index.update': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/artikel/index.update').default>>>>
    }
    '/api/lawyers': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lawyers/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lawyers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lawyers/index.post').default>>>>
    }
    '/api/lawyers/index.update': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lawyers/index.update').default>>>>
    }
    '/api/users/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/api/users/index.update': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.update').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}